# Generated by Django 3.2.8 on 2021-10-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
